sudo: required

language: cpp
services:
  - docker

before_install:
  - docker pull ubuntu:16.04 

install:
 - sudo add-apt-repository -y ppa:jonathonf/gcc-7.1
 - sudo apt-get update
 - sudo apt-get install gcc-7 
 - sudo apt-get install g++-7 

script: "bash -c ./scripts/travis/ubuntu-16-build.sh"
 
