language: cpp

os:
  - linux

dist: trusty

compiler: 
     - gcc

# whitelist
branches:
  only:
    - master


before_install:
   # conditional preparation for OSX 
   if [ ${TRAVIS_OS_NAME} == 'linux' ]; 
   then 
     echo "running linux"

     sudo update-alternatives --remove-all gcc 
     sudo update-alternatives --remove-all g++

     sudo add-apt-repository ppa:jonathonf/gcc-7.1
     sudo apt-get update

     sudo apt-get -V install gcc-7 g++-7
     sudo update-alternatives --config gcc
     sudo update-alternatives --config g++


     sudo apt-get remove -qq cmake cmake-data
     sudo apt-get install cmake cmake-data;
     sudo apt-get install software-properties-common;
   fi
 
install:
  #  gcc 7.1
  #- if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 10; fi
  #- if [ "$CXX" == "g++" ]; then  sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 10; fi
  
 
script:
  - pwd
  - which gcc
  - gcc --version
  - which g++
  - g++ --version
  - mkdir build && cd build
  - cmake ..
  - make -j
  #- make test


 