language: cpp

os:
  - linux

dist: trusty
sudo: required

compiler: 
     - gcc

# whitelist
branches:
  only:
    - master

  
install:
  - echo $TRAVIS_OS_NAME
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then apt show g++-6; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install gcc-6 g++-6; fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7.1 20; fi
#  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7.1 20; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --config gcc; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --config g++; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get remove -qq cmake cmake-data; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install cmake cmake-data; fi
  
script:
  - pwd
  - which gcc
  - gcc --version
  - which g++
  - g++ --version
  - which gcc-6
  - locate gcc-6
  - mkdir build && cd build
  - cmake ..
  - make 
  #- ctest --output-on-failure


 