language: cpp
sudo: required
compiler: gcc
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

# whitelist
branches:
  only:
    - master

 
install:
  - echo $TRAVIS_OS_NAME
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
 
script:

  - pwd
  - which g++
  - g++ --version
  - git clone https://github.com/ericniebler/range-v3.git
  - sudo cp -r range-v3/include/* /usr/local/include/.
  - mkdir build && cd build
  - cmake ..
  - make -j
  # until we have unit tests. find all executables and run them
  - rm -rf CMake*
  - find . -type f -executable -exec '{}' ';' 
  #- ctest --output-on-failure


 
