language: cpp
sudo: required
compiler: gcc
dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

# whitelist
branches:
  only:
    - master

 
install:
  - echo $TRAVIS_OS_NAME
  - sudo apt-get install -qq gcc-7 g++-7 
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90 
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
 

script: "bash -c ./scripts/travis/ubuntu-16-build.sh"
 
